
## arg 1:  the new package version
post_install() {
  ldconfig
  if [ -r /etc/qubes-release ]; then
      # dom0
      /bin/systemctl enable qubes-meminfo-writer-dom0.service > /dev/null 2>&1
  else
      # VM
      /bin/systemctl enable qubes-meminfo-writer.service > /dev/null 2>&1
  fi
}

post_upgrade() {
  ldconfig
}

post_remove() {
  ldconfig
  /bin/systemctl disable qubes-meminfo-writer.service > /dev/null 2>&1
  /bin/systemctl disable qubes-meminfo-writer.service > /dev/null 2>&1
}

