#!/bin/sh
#
# The Qubes OS Project, http://www.qubes-os.org
#
# Copyright (C) 2015  Marek Marczykowski-Górecki
#                       <marmarekp@invisiblethingslab.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
#

set -e

basedir=/var/lib/qubes/vm-kernels

function build_modules_img() {
    kver=$1
    initramfs=$2
    output_file=$3

    mkdir /tmp/qubes-modules-$kver
    truncate -s 400M /tmp/qubes-modules-$kver.img
    mkfs -t ext3 -F /tmp/qubes-modules-$kver.img > /dev/null
    mount /tmp/qubes-modules-$kver.img /tmp/qubes-modules-$kver -o loop
    cp -a -t /tmp/qubes-modules-$kver /lib/modules/$kver
    cp "/boot/vmlinuz-$kver" "/tmp/qubes-modules-$kver/vmlinuz"
    cp "$initramfs" "/tmp/qubes-modules-$kver/initramfs"
    umount /tmp/qubes-modules-$kver
    rmdir /tmp/qubes-modules-$kver
    mv /tmp/qubes-modules-$kver.img $output_file
}

function build_initramfs() {
    kver=$1
    output_file=$2

    dracut --nomdadmconf --nolvmconf --force \
        --modules "kernel-modules qubes-vm-simple" \
        --conf /dev/null --confdir /var/empty \
        -d "xenblk xen-blkfront cdrom ext4 virtio virtio_blk jbd2 crc16 dm_snapshot" \
        $output_file $kver
    chmod 644 "$output_file"
}

if [ -z "$1" ]; then
    echo "Usage: $0 <kernel-version> [<display-kernel-version>]" >&2
    exit 1
fi

if [ ! -r /boot/vmlinuz-$1 -o ! -d /lib/modules/$1 ]; then
    echo "ERROR: Kernel version $1 not installed" >&2
    exit 1
fi

kernel_version=$1
if [ -n "$2" ]; then
    output_dir="$basedir/$2"
else
    output_dir="$basedir/$kernel_version"
fi

echo "--> Building files for $kernel_version in $output_dir"

mkdir -p "$output_dir"
cp "/boot/vmlinuz-$kernel_version" "$output_dir/vmlinuz"
echo "---> Generating initramfs"
build_initramfs "$kernel_version" "$output_dir/initramfs"
echo "---> Generating modules.img"
build_modules_img "$kernel_version" "$output_dir/initramfs" \
    "$output_dir/modules.img"

echo "--> Done."
