#!/bin/sh

# FIXME: Ignore USB hubs.
[ "`echo $TYPE | cut -f1 -d/`" = "9" ] && exit 0

NAME=`basename ${DEVPATH} | tr . _`
QDB_KEY="/qubes-usb-devices/$NAME/"

qubesdb-rm "$QDB_KEY"
# This is meant to trigger watches
qubesdb-write /qubes-usb-devices ''
