#!/bin/sh

NAME=${DEVNAME#/dev/}
QDB_KEY="/qubes-block-devices/$NAME"
# Trailing slash is intentional - it will remove the whole directory, instead of
# a single base entry
qubesdb-rm "$QDB_KEY/"
# This is meant to trigger watches
qubesdb-write /qubes-block-devices ''

if [ -r /run/qubes/block-slave-cache-$NAME ]; then
    # update info about underlying devices of device-mapper (if any);
    for dev in $(cat /run/qubes/block-slave-cache-$NAME); do
        udevadm trigger /sys/class/block/$dev
    done
    rm -f /run/qubes/block-slave-cache-$NAME
fi
